# ==============================================================================
# Fail2ban Filter: Match HTTP 429 Too Many Requests & 401 Unauthorized
# ==============================================================================
[Definition]
failregex = ^<HOST> - .* "(?:POST|GET|PUT|PATCH|DELETE) .* HTTP/.*" (?:429|401) .*$
ignoreregex =
