ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ com.payroll.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/payroll_insight_db"
    url = ${?DB_URL}
    driver = "org.postgresql.Driver"
    user = "postgres"
    user = ${?DB_USER}
    password = "1234"
    password = ${?DB_PASSWORD}
    maximumPoolSize = 10
    maximumPoolSize = ${?DB_MAX_POOL_SIZE}
}

jwt {
    secret = "payroll-insight-pro-super-secure-jwt-secret-key-2026"
    secret = ${?JWT_SECRET}
    issuer = "com.payroll.insight"
    issuer = ${?JWT_ISSUER}
    audience = "payroll-app-users"
    audience = ${?JWT_AUDIENCE}
    realm = "Payroll Insight Pro"
    realm = ${?JWT_REALM}
}
