/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f7fafc",
        "surface-container-highest": "#e0e3e5",
        "surface-container": "#ebeef0",
        "secondary-fixed-dim": "#99cbff",
        "on-primary-fixed-variant": "#00504d",
        "tertiary-fixed": "#d4e4fc",
        "tertiary-container": "#93a2b9",
        "inverse-on-surface": "#eef1f3",
        "on-tertiary-container": "#2a394c",
        "on-tertiary": "#ffffff",
        "on-background": "#181c1e",
        "on-primary-container": "#003f3d",
        "surface-container-high": "#e5e9eb",
        "on-error": "#ffffff",
        "on-surface": "#181c1e",
        "error-container": "#ffdad6",
        "on-secondary-container": "#004470",
        "on-surface-variant": "#3d4948",
        "tertiary": "#515f74",
        "on-secondary-fixed": "#001d34",
        "on-tertiary-fixed": "#0d1c2e",
        "surface-container-low": "#f1f4f6",
        "on-error-container": "#93000a",
        "outline-variant": "#bcc9c7",
        "tertiary-fixed-dim": "#b8c8e0",
        "surface-dim": "#d7dadc",
        "primary-fixed": "#84f5ee",
        "surface-tint": "#006a66",
        "outline": "#6d7a78",
        "secondary": "#00629d",
        "on-primary-fixed": "#00201e",
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#66d8d2",
        "on-tertiary-fixed-variant": "#39485c",
        "on-secondary-fixed-variant": "#004a78",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#cfe5ff",
        "primary-container": "#38b2ac",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "primary": "#006a66",
        "secondary-container": "#61b4fd",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#66d8d2",
        "surface-bright": "#f7fafc",
        "surface": "#f7fafc"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "32px",
        "gutter": "24px",
        "unit": "4px",
        "card-padding": "24px",
        "margin-mobile": "16px",
        "table-cell-padding": "16px 20px"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "'Cairo'", "'Outfit'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "'Cairo'", "'Outfit'", "sans-serif"],
        mono: ["'Plus Jakarta Sans'", "'JetBrains Mono'", "monospace"],
        "title-md": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "'Cairo'", "monospace"],
        "data-tabular": ["'Plus Jakarta Sans'", "'Cairo'", "sans-serif"]
      },
      boxShadow: {
        "soft": "0 4px 6px -1px rgba(56, 178, 172, 0.05), 0 10px 15px -3px rgba(56, 178, 172, 0.1)",
        "ambient": "0 0 20px rgba(56, 178, 172, 0.15), 0 4px 6px rgba(0, 106, 102, 0.1)"
      }
    },
  },
  plugins: [],
}
